### PR TITLE
#19: community section

### PR DESCRIPTION
**Pull request by jasonmadigan**
#19 - Created a new Community Page

* Added a new Community page, with content on how to contribute to the project
* Moved content to `src`, to avoid the root directory becoming a dumping ground
* Added eleventy-navigation plugin
* Added notes on our mailing list(s)
* Added a `security.txt`

### CODE REVIEW

**Comment by thomasmaas** [comment]
@jasonmadigan Any chance you could share a screenshot for a lazy reviewer?

**Comment by jasonmadigan** [comment]
@thomasmaas you've reminded me, we could do with a staging area - but here you go:

Screenshot 2023-07-04 at 12 28 21

**Review by thomasmaas — APPROVED** [review]
Design-wise it could use some love. This template doesn't come with more design?

**Comment by jasonmadigan** [comment]
thanks @thomasmaas - yeah, it does have a bunch of re-usable elements which might make this a bit more appealing. this iteration was a bit more focused on the content. I'll submit another PR with some design tweaks a little later.

**Pull request merged**
