### PR TITLE
Add blog nav with initial post

### PR DESCRIPTION
**Pull request by david-martin**
* Adds a new blog top nav page that shows blog posts
* Adds a first blog post to announce the CNCF sandbox project acceptance - posts go in the src/blog folder with metadata at top of md file
* Removes the anchor id links for Features, Components & FAQs from the top nav and 'Useful Links' at the bottom to make room for the Blog nav item
* Styling changes and icon addition to the top nav (see comparison screenshot)

Nav before:
image

Nav after:
image

@jasonmadigan I'd appreciate any suggestions on how to make the blog landing page a little nicer looking. Any suggestions on the individual blog post page are also welcome.

The blog layout & template is partially copied from https://github.com/11ty/eleventy-base-blog/tree/main (MIT licence)

### CODE REVIEW

**Review by jasonmadigan — APPROVED** [review]
Nice, this all looks good to me. Not for now, but if we do have a lot of posts, we may want to look at pagination.

**Comment by david-martin** [comment]
> Nice, this all looks good to me. Not for now, but if we do have a lot of posts, we may want to look at pagination.

yeah, that makes sense.
I'm toying with this as the layout for the top blog landing page.
Thoughts?
Maybe remove the numbering

image

**Pull request merged**
